# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        shell: bash
        run: |
          echo Add other actions to build
          echo "TEST_PARAM=${{ github.workspace }}" >> $GITHUB_ENV

      - uses: e-marchand/test-github-ci-stuff@main
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        with:
          param1: '{"path": "test", "env": "${{ env.TEST_PARAM }}" }'
          param2: '{"path": "test", "github": "${{ github.workspace }}" }'
          param3: '{"path": "test", "githubenv": "${{ env.GITHUB_WORKSPACE }}" }'
