name: junit
on:
  workflow_dispatch:
permissions:
    contents: read
    checks: write
    id-token: write
jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'junit/TEST-*.xml'
          commit: ${{github.event.workflow_run.head_sha}}
